### ISSUE TITLE
Setting default url to home directory

### ISSUE THREAD

**Issue by Amerterasu** [jupyterhub/jupyterhub#929]
I understand that there is a way to configure the default url in the config file, but this involves something along the line of adding "/tree/home/{username}". However I've encountered a situation where the username is not the same as the one in path to home. Is there a way to instead do a "/tree/{homedir}" or something along the line of getting the home directory for a user? Thanks!

**Comment by willingc** [comment]
Hi @Amerterasu,

[This section](https://jupyterhub.readthedocs.io/en/latest/troubleshooting.html#i-want-access-to-the-whole-filesystem-but-still-default-users-to-their-home-directory) in the docs demonstrates setting `c.Spawner.notebook_dir` and `c.Spawner.default_url`. Here's also a link to the docstrings for the Spawner settings for `notebook_dir` and `default_url` https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L232

I believe that using both together will allow you to customize as desired. Please let us know if you need additional info/guidance.

**Comment by Amerterasu** [comment]
Hi thanks for the link and it does work, but in the link you gave me for the `c.Spawner.notebook_dir` the description says that '~' gets expanded to the home directory. Is there a similar feature for the `c.Spawner.default_url` ? I know you can set the default url to home by doing '/home/{username}' , but as my first post explained, what if there are a set of users where the home directories are not named using their username.

**Comment by anderbubble** [comment]
Please reopen this.

I don't think @Amerterasu's point was addressed. Unless there's something we're missing, there doesn't appear to be a way to set `default_url` to the user's home directory without making structural assumptions about where user home directories are on the system.

**Comment by minrk** [comment]
> Unless there's something we're missing, there doesn't appear to be a way to set default_url to the user's home directory without making structural assumptions about where user home directories are on the system.

That's correct. JupyterHub *can't* make structural assumptions about home directories, but individual deployments can. Since setting the default URL to the home directory requires making assumptions about notebook_dir and knowledge of the system, I think this is best done in `jupyter_notebook_config.py` on the system, which can have Python logic. I believe this should do it:

```python
# in /etc/jupyter/jupyter_notebook_config.py
import os
home_dir = os.path.expanduser('~')
c.SingleUserNotebookApp.default_url = '/tree' + home_dir
c.SingleUserNotebookApp.notebook_dir = '/'
```

What this does:

1. locate the home directory of the user
2. set default_url to `/tree/$HOME` (assumes notebook_dir is root)
3. set notebook_dir to `/` (satisfy assumption in 2.)
4. only apply this configuration to notebook servers run via jupyterhub (`SingleUserNotebookApp` as opposed to `NotebookApp`, which would apply to all notebook servers)

**Comment by abalter** [comment]
@minrk I have a `.local/share/jupyter/runtime` folder with a file called `nbserver-1233.json` that looks like:

```
balter@balterbox:~$ cat .local/share/jupyter/runtime/nbserver-1233.json
{
  "base_url": "/user/balter/",
  "hostname": "127.0.0.1",
  "notebook_dir": "/home/balter/jupyter",
  "password": false,
  "pid": ####,
  "port": #####,
  "secure": ####,
  "token": "####",
  "url": "http://127.0.0.1:#####/user/balter/"
}
```

I installed jupyterhub with conda, and started it as _balter_ with `jupyterhub`.

_notebook_dir_ was originally just _home_balter_, but I changed it. Notebook still defaults to _home_balter_.

**Comment by abalter** [comment]
Is this related? https://github.com/jupyterhub/jupyterhub/issues/203

**Comment by vivekbiet** [comment]
Hi,
This is still not resolved, i have added the property 
c.Spawner.notebook_dir = '/assignments' 

i am not keeping it as home directory of user which is logged in. This is not working for me

**Comment by bjyxmas** [comment]
I recently had a chance to setup a jupyterhub environment for multi-users.
And I did not want logged-in users to see their home directory as they login.
And I found the easiest(at least for me) solution from here:
https://jupyterhub.readthedocs.io/en/stable/getting-started/config-basics.html

here is the answer:
$ jupyterhub --Spawner.notebook_dir='~/notes'

(instead of '~/notes' just use any of your preferences)

**Comment by kylrth** [comment]
This worked for me under the Jupyter Lab Hub extension:

```
c.Spawner.notebook_dir = '~'
c.Spawner.default_url = ''
```

My users log into their Jupyter Lab server and see their home directory, as I wanted.
